version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  user-service:
    build: ./backend/services/user-service
    ports:
      - "5001:5001"
  baby-service:
    build: ./backend/services/baby-service
    ports:
      - "5002:5002"
  gateway:
    build: ./backend/gateway
    ports:
      - "4000:4000"
